TC_NAME = syno-$(TC_ARCH)

TC_ARCH = hi3535
TC_VERS = 6.2.2
TC_OS_MIN_VER = 6.2.2-24922
TC_KERNEL = 3.4.35+

TC_DIST = hi3535-gcc483_glibc219_hi3535-GPL
TC_EXT = txz
TC_DIST_NAME = $(TC_DIST).$(TC_EXT)
TC_DIST_SITE = https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%206.2.2%20Tool%20Chains/HiSilicon%20Hi3535%20Linux%203.4.35

TC_BASE_DIR = arm-cortexa9-linux-gnueabi
TC_INCDIR = $(TC_BASE_DIR)/sysroot/usr/include
TC_LIBDIR = $(TC_BASE_DIR)/sysroot/lib

include ../../mk/spksrc.tc.mk
