TC_NAME = syno-x64

TC_ARCH = apollolake avoton braswell broadwell broadwellnk bromolow cedarview denverton dockerx64 geminilake grantley purley kvmx64 x86 x86_64
TC_VERS = 6.2
TC_OS_MIN_VER = 6.2-22259
TC_KERNEL = 3.10.105+

TC_DIST = x64-gcc493_glibc220_linaro_x86_64-GPL
TC_EXT = txz
TC_DIST_NAME = $(TC_DIST).$(TC_EXT)
TC_DIST_SITE = https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%206.2%20Tool%20Chains/Intel%20x86%20linux%203.10.102%20%28Pineview%29

TC_BASE_DIR = x86_64-pc-linux-gnu

include ../../mk/spksrc.tc.mk
