TC_NAME = syno-$(TC_ARCH)

TC_ARCH = 88f6281
TC_VERS = 6.1
TC_OS_MIN_VER = 6.1-15047
TC_KERNEL = 2.6.32.12+

TC_DIST = 6281-gcc464_glibc215_88f6281-GPL
TC_EXT = txz
TC_DIST_NAME = $(TC_DIST).$(TC_EXT)
TC_DIST_SITE = https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%206.1%20Tool%20Chains/Marvell%2088F628x%20Linux%202.6.32

TC_BASE_DIR = arm-marvell-linux-gnueabi
TC_INCDIR = $(TC_BASE_DIR)/libc/usr/include
TC_LIBDIR = $(TC_BASE_DIR)/libc/lib

include ../../mk/spksrc.tc.mk
