TC_NAME = syno-$(TC_ARCH)

TC_ARCH = denverton
TC_VERS = 6.2.2
TC_OS_MIN_VER = 6.2.2-24922
TC_KERNEL = 4.4.59+

TC_DIST = denverton-gcc493_glibc220_linaro_x86_64-GPL
TC_EXT = txz
TC_DIST_NAME = $(TC_DIST).$(TC_EXT)
TC_DIST_SITE = https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%206.2.2%20Tool%20Chains/Intel%20x86%20Linux%204.4.59%20%28Denverton%29

TC_BASE_DIR = x86_64-pc-linux-gnu

include ../../mk/spksrc.tc.mk
