TC_NAME = syno-aarch64

TC_ARCH = rtd1296 armada37xx aarch64
TC_VERS = 6.1
TC_OS_MIN_VER = 6.1-15047

TC_DIST = rtd1296-gcc494_glibc220_armv8-GPL
TC_EXT = txz
TC_DIST_NAME = $(TC_DIST).$(TC_EXT)
TC_DIST_SITE = https://sourceforge.net/projects/dsgpl/files/Tool%20Chain/DSM%206.1%20Tool%20Chains/Intel%20x86%20Linux%204.4.15%20%28Rtd1296%29

TC_BASE_DIR = aarch64-unknown-linux-gnueabi
TC_INCDIR = $(TC_BASE_DIR)/sysroot/usr/include
TC_LIBDIR = $(TC_BASE_DIR)/sysroot/lib

include ../../mk/spksrc.tc.mk
